# Generated by Django 4.0 on 2021-12-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygreen', '0002_rename_customerdetails_customerdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetail',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
