# Generated by Django 4.0 on 2021-12-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygreen', '0003_customerdetail_name_customerdetail_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetail',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
