# Generated by Django 4.0 on 2021-12-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygreen', '0004_customerdetail_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='contactnumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
