# Generated by Django 4.0 on 2021-12-20 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mygreen', '0005_alter_customerdetail_contactnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='profilepic',
            field=models.ImageField(blank=True, default='profileimage.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
