# Generated by Django 4.0 on 2021-12-21 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygreen', '0008_alter_product_productprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productbuypic4',
        ),
    ]
