# Generated by Django 4.0 on 2021-12-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygreen', '0009_remove_product_productbuypic4'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offerprice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='soiltype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
