# Generated by Django 4.0 on 2021-12-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygreen', '0014_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentmode',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
