# Generated by Django 4.0 on 2021-12-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygreen', '0016_alter_order_paymentmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentmode',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
