# Generated by Django 4.0 on 2021-12-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygreen', '0018_order_productname_alter_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetail',
            name='address',
            field=models.CharField(blank=True, default='update your address', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='contactnumber',
            field=models.CharField(blank=True, default='update your contactnumber', max_length=10, null=True),
        ),
    ]
