# Generated by Django 4.0 on 2021-12-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygreen', '0019_customerdetail_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='contactnumber',
            field=models.CharField(blank=True, default='No contact', max_length=10, null=True),
        ),
    ]
