# Generated by Django 4.0 on 2021-12-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygreen', '0022_alter_customerdetail_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='address',
            field=models.CharField(blank=True, default='update address', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='contactnumber',
            field=models.CharField(blank=True, default='update contact', max_length=25, null=True),
        ),
    ]
